name: GitHub Actions Demo
run-name: ${{ github.actor }} is publishing artifact 🚀
env:
  GH_TOKEN: ${{ github.token }}
on: 
  release:
    types: [published]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: pip install pyinstaller
      - run: echo 'pyinstaller installed'
      - run: pyinstaller -F app.py
      - run: ls dist
      - run: cp -r template dist/template
      - run: mv dist/app.exe dist/文档生成器.exe
      - run: Compress-Archive -Path dist -Destination 文档生成器.zip
      - run: ls
      - name: Upload asset files to release ${{  github.ref_name }}
        run: gh release upload ${{  github.ref_name }} 文档生成器.zip
      
